### ISSUE TITLE
为何不会自动滚动？

### ISSUE THREAD

**Issue by hongguilong** [weilao/vue-swiper#16]
Loop我都设置了true。还是不会自动滚动？看了版主的demo，好像是不支持自动滚动的。但是为何loop说可以自动滚动？

**Comment by ValorLin** [comment]
loop 是指从最后一张往后继续滑能切换回第一张。

**Comment by hongguilong** [comment]
所以说，目前这个插件是不支持自动播放的?

**Comment by ValorLin** [comment]
是的，有两种方案推荐你使用：
1. 打开 loop 选项，使用 setInterval() 设置定时器，定时调用 next() 方法。
2. Fork 此项目，自行修改源码添加自动播放功能。
