### ISSUE TITLE
使用组件时报错了，use the "name" option for better debugging messages

### ISSUE THREAD

**Issue by nk097** [weilao/vue-swiper#17]
开发环境：vue2.0
按照github上的指引安装了是wiper组件，使用的时候出现报错了：
[Vue warn]: Failed to resolve directive: el 
(found in <Anonymous> - use the "name" option for better debugging messages.)

请问应该如何解决？

**Comment by ValorLin** [comment]
这个支持 1.0 的，可以尝试一下这个 #7 里面其他人提供的 2.0 版本。
