### ISSUE TITLE
可以添加分页吗？

### ISSUE THREAD

**Issue by fengtaijun0507** [weilao/vue-swiper#2]

**Comment by ValorLin** [comment]
不知道你指的是哪种分页，可以描述一下吗？

**Comment by fengtaijun0507** [comment]
轮播的时候会有一排圆点，随着图片移动而移动！

**Comment by fengtaijun0507** [comment]
还有就是您这个支持无缝切换

**Comment by ValorLin** [comment]
@fengtaijun0507 小圆点我懂了，有时间的话会添加进去。
现阶段自行实现也比较容易，只要自己定义好html结构和样式，然后通过监听 slide-change-start 或 slide-change-end 事件，及时更改小圆点状态就行。

无缝切换没看明白，能麻烦解释一下吗？

**Comment by fengtaijun0507** [comment]
好的，有时间我试一下怎么加圆点。无缝切换，可能我自己叫着顺口，不好意思啊！就是第一页切换到最后一页，最后一页切换到第一页，这之间的切换实现。

**Comment by ValorLin** [comment]
v0.4.0 版本新增小圆点 @fengtaijun0507 
循环切换的功能我会再抽时间做一下。

**Comment by ValorLin** [comment]
0.5.0 添加了循环支持
