### ISSUE TITLE
loop 可以添加循环么

### ISSUE THREAD

**Issue by ycr6708536** [weilao/vue-swiper#4]
可以添加循环么

**Comment by ValorLin** [comment]
没问题。

**Comment by ycr6708536** [comment]
循环，我看着源码，是使用Translate 实现的，我直接使用setPage 方法扩展后是从最后一张倒序循环到第一张，这种方式不太友好，期望可以添加从最后一张直接循环到第一张。

**Comment by ValorLin** [comment]
0.5.0 添加了循环支持
